# Site settings
title: The Shifting
header-img: img/home-bg.jpg
email: info@theshifting.ca
description: "We shift around Vancouver."
url: "http://www.theshifting.ca"
twitter_username: ShiftingCa
github_username:  theShifting
facebook_username:  TheShifting

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

authors:
  onzo:
    display_name: Ridia Onzo
    email: obj.art@onzo.ca
    web: http://www.onzo.ca/
    twitter: ONZOart
    github: adriandgr
  rhys:
    display_name: Rhys Edwards
    email: info@theshifting.ca
    twitter: Rhy5Edwards
    github: theShifting
